development:
  adapter: postgresql
  database: antrouter_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: antrouter_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: antrouter_production
  pool: 5
  timeout: 5000
