# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8caca54ad0cbc0f759cb7ab357a5f3b2b6396b7cfd303b5d6fe13003af3e8d549fa4b419d84f0a155d87dc3df079ea9b8e8318275245087c0bef2a0e64578800

test:
  secret_key_base: 97a2b626b8879d4db9c41af851cd30b891aff4f49d8c50d7b55dfec2340144e92297d9e2b73fa308ed397d0dadcf9ed535957f4257b79e334c45cd4a28f2cee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
